name: 260c
channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - torchvision
  - pytorch-cuda=11.7
  - pytorch
  - torchaudio
  - backcall
  - python=3.11
  - ca-certificates
  - psutil
  - _libgcc_mutex
  - ncurses
  - asttokens
  - libffi
  - xz
  - parso
  - wheel
  - tk
  - backports.functools_lru_cache
  - packaging
  - readline
  - libnsl
  - backports
  - pickleshare
  - six
  - typing-extensions
  - stack_data
  - comm
  - prompt-toolkit
  - bzip2
  - libsqlite
  - nest-asyncio
  - libexpat
  - libuuid
  - zipp
  - importlib-metadata
  - debugpy
  - libzlib
  - jupyter_core
  - ld_impl_linux-64
  - executing
  - pyzmq
  - jupyter_client
  - libstdcxx-ng
  - jedi
  - pip
  - ptyprocess
  - pygments
  - wcwidth
  - pexpect
  - python-dateutil
  - traitlets
  - libgcc-ng
  - tzdata
  - importlib_metadata
  - libsodium
  - openssl
  - zeromq
  - typing_extensions
  - platformdirs
  - setuptools
  - matplotlib-inline
  - python_abi
  - prompt_toolkit
  - ipython
  - zstd
  - decorator
  - llvm-openmp
  - pure_eval
  - tornado
  - _openmp_mutex
  - ipykernel
  - matplotlib
  - joblib
  - seaborn
  - ipywidgets
  - jupyter
  - tokenizers
  - datasets
  - certifi
  - transformers
  - objgraph
